# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: vinayBuildWorkflow

on:
  push:
    branches:
      - master  # Adjust to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11 
        distribution: 'adopt'

    - name: Generate Gradle wrapper
      run: |
        chmod +x gradlew
        ./gradlew wrapper
      working-directory: vinayraj739/HoussemDellai-gs-spring-boot

    - name: Build with Gradle
      run: |
        ./gradlew build  # Adjust the Gradle build command as needed
      working-directory: vinayraj739/HoussemDellai-gs-spring-boot
